config/routes.rb
Rails.application.routes.draw do
  get 'terms_and_conditions', to: "static_pages#terms_and_conditions", as: "terms_and_conditions"
  get 'privacy_policy', to: "static_pages#privacy_policy", as: "privacy_policy"
  get 'community_guidelines', to: "static_pages#community_guidelines", as: "community_guidelines"
  resources :organizations, except: [:destroy] do
    get :autocomplete_organization_name, on: :collection
    resources :rants, shallow: true, except: [:edit, :destroy, :update]
    collection do
      match 'search' => 'organizations#search', via: [:get, :post], as: :search
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :rants

  validates :name, presence: true, uniqueness: true
end

app/models/rant.rb
class Rant < ApplicationRecord
  belongs_to :organization
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_global_search_variable

  def set_global_search_variable
    @q = Organization.search(params[:q])
  end

  def search
    index
    render :index
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @rants = Rant.all.order("created_at DESC").limit(6)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  autocomplete :organization, :name, full: true

  # GET /organizations
  # GET /organizations.json
  def index
    @q = Organization.ransack(params[:q])
    @organizations = @q.result(distinct: true)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @rants = @organization.rants.order("created_at DESC")
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :desc)
    end
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  before_action :set_organization, except: [:show]
  before_action :set_rant, only: [:edit, :update, :destroy]
  # GET /rants
  # GET /rants.json
  def index
    @rants = @organization.rants
  end

  # GET /rants/1
  # GET /rants/1.json
  def show
    @rant = Rant.find(params[:id])
  end

  # GET /rants/new
  def new
    @rant = Rant.new
  end

  # GET /rants/1/edit
  def edit
  end

  # POST /rants
  # POST /rants.json
  def create
    @rant = Rant.new(rant_params)

    respond_to do |format|
      if @rant.save
        format.html { redirect_to @rant.organization, notice: 'Rant was successfully created.' }
        format.json { render :show, status: :created, location: @rant.organization }
      else
        format.html { render :new }
        format.json { render json: @rant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rants/1
  # PATCH/PUT /rants/1.json
  def update
    respond_to do |format|
      if @rant.update(rant_params)
        format.html { redirect_to @rant.organization, notice: 'Rant was successfully updated.' }
        format.json { render :show, status: :ok, location: @rant.organization }
      else
        format.html { render :edit }
        format.json { render json: @rant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rants/1
  # DELETE /rants/1.json
  def destroy
    @rant.destroy
    respond_to do |format|
      format.html { redirect_to rants_url, notice: 'Rant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rant
      @rant = @organization.rants.find(params[:id])
    end

    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rant_params
      params.require(:rant).permit(:organization_id, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def terms_and_conditions
  end

  def privacy_policy
  end

  def community_guidelines
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end

  def default_meta_tags
    {
      twitter: {image: "https://elasticbeanstalk-ap-southeast-1-740434333056.s3-ap-southeast-1.amazonaws.com/spillstreet.PNG", card: "summary"},
      og: {image: "https://elasticbeanstalk-ap-southeast-1-740434333056.s3-ap-southeast-1.amazonaws.com/spillstreet.PNG"}
    }
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#ed495e">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#ed495e">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ed495e">

app/views/landing/index.html.erb
<% content_for :head do %>
<%= display_meta_tags og: { title: "Spill Street", description: "Anonymously rant about your orgs" } %>
<%= display_meta_tags twitter: { title: "Spill Street", description: "Anonymously rant about your orgs" } %>
<% end %>

<% title "Anonymously Rant About Your Orgs"%>
<section class = "hero is-danger">
  <div class = "hero-body">
    <div class = "container has-text-centered">
      <div>
        <%= image_tag "logo.png",width: "20%"%>
      </div>
      <h1 class = "title is-1">
        Rant about your orgs
      </h1>
      <p class = "subtitle">
        Anonymously post and rant about your orgs
      </p>
      <div class = "has-text-centered">
          
      Use this search bar to look for an org
      <div style= "width:50%; margin:0 auto;">
        <%= render "shared/search-input"%>
      </div>
      </div>
    </div>
  </div>
</section>
<section class = "section ">
  <div class="container">
    <h3 class="title is-2 has-text-centered">Recent Rants</h3>
    <div class="columns is-multiline is-desktop">
      <% @rants.each do |rant| %>
        <div class="column is-half-desktop">
          <%= render "rants/rant", rant: rant %>
        </div>

      <% end %>
    </div>

  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= (yield(:title) + " | ").to_s %>
      <% end %>
      Spill Street
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% if content_for?(:head) %>
    <%= yield(:head) %>
    <% end %>
    <%= display_meta_tags(default_meta_tags)%>

    <%= render 'application/favicon' %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-93585080-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-93585080-2');
    </script>
  </head>

  <body>
    <nav class="navbar is-danger" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
          <%= image_tag "logo.png"%>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu" id="navMenu">
        <div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Organizations
            </a>

            <div class="navbar-dropdown">
              <%= link_to "Add an Organization", new_organization_path, class: 'navbar-item' %>
              <%= link_to "View all organizations", organizations_path, class: "navbar-item" %>
            </div>
          </div>
        </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <%= search_form_for @q do |f| %>
                <div class="field">
                  <p class = "control has-icons-left">
                    <span class = "icon is-left">
                      <%= fa_icon "search" %>

                    </span>
                    <%= f.text_field :name_cont, placeholder: "Search Orgs", class: 'input search-query', type: "search", "data-autocomplete"  => autocomplete_organization_name_organizations_path%>
                  </p>

                </div>
              <% end %>
            </div>

          </div>

      </div>
    </nav>
    <% if notice %>
      <div class = "notification is-primary" role= "alert">
        <a href="#" class="delete" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="notification is-danger" role="alert">
        <a href="#" class="delete" data-dismiss="alert" aria-label="close">&times;</a>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Organization Name' %>
    <%= form.text_field :name, class: "input", placeholder: "Name of organization" %>
  </div>

  <div class="field">
    <%= form.label :desc, "Description of Organization" %>
    <%= form.text_area :desc, rows: "7", class: "textarea", placeholder: "Give a short description of the organization" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "button is-primary" %>
  </div>
<% end %>

app/views/organizations/_organization-header.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <div class="media">
        <div class="media-left">
          <figure class="image is-128x128">
            <img class = "is-rounded "src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
          </figure>
        </div>
        <div class="media-content">
          <p class="title"><%= organization.name %></p>
          <div class="content"><%= simple_format organization.desc %></div>
        </div>
      </div>


    </div>
</section>

app/views/organizations/_organization.html.erb
<%= link_to organization do %>
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-2"><%= organization.name %></p>
      </div>
    </div>

    <div class="content">
      <%= simple_format organization.desc %>
    </div>
  </div>
</div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<% title "Organizations" %>
<section class = "section">
  <div class="containers">
    <h1 class = "title has-text-centered">Organizations</h1>


    <div style = "padding:20px;">
      <%= render "shared/search-input"%>
    </div>
    <div class="columns is-multiline">
      <% @organizations.each do |organization| %>
        <div class="column is-full">
        <%= render "organizations/organization", organization: organization %>
        
        </div>
      <% end %>
    </div>
      <div class = "has-text-centered">
        Can't find your org? <%= link_to "Click here to add it", new_organization_path %>
      </div>



  </div>

</section>

app/views/organizations/new.html.erb
<section class="section">
  <div class="container">
    <h1 class='title has-text-centered'>New Organization</h1>

    <%= render 'form', organization: @organization %>



  </div>
</section>

app/views/organizations/show.html.erb
<% content_for :head do %>
<%= display_meta_tags og: { title: @organization.name + " | Spillstreet", description: "Rant about " + @organization.name } %>
<%= display_meta_tags twitter: { title: @organization.name + " | Spillstreet", description: "Rant about " + @organization.name } %>
<% end %>

<% title @organization.name %>
<%= render "organizations/organization-header", organization: @organization %>
<section class="section">
  <div class="container">
    <h2 class = "title is-4">
      Need to rant?
    </h2>
      <%= render "rants/form", organization: @organization, rant: Rant.new %>
  </div>
</section>
<section class="section">
  <div class="container">
    <h3 class="title is-1 has-text-centered">
      Rants
    </h3>
    <p class = "subtitle has-text-centered">
      <%= @organization.rants.count %> rants so far...
    </p>
    <div class="columns is-multiline">
      <% @rants.each do |rant| %>
      <div class="column is-full">
        <%= render "rants/rant", rant: rant %>
    </div>
      <% end %>
      </div>
  </div>
</section>

app/views/rants/_form.html.erb
<%= form_for([organization, rant], local: true) do |form| %>
  <% if rant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rant.errors.count, "error") %> prohibited this rant from being saved:</h2>

      <ul>
      <% rant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :organization_id, value: @organization.id %>

  <div class="field" style= "margin-bottom: 0;">
    <%= form.text_area :body, class: "textarea", rows: "5", placeholder: "Rant out your feelings, talk shit, spill tea, let everything out here"%>

    <div class = "has-text-right">
      <small>
      By clicking Submit Rant, you agree to our <%= link_to "Terms and Conditions", terms_and_conditions_path %>, <%= link_to "Privacy Policy", privacy_policy_path %>, and our <%= link_to "Community Guidelines", community_guidelines_path %>
      </small>
  </div>
  </div>


  <div class="field is-grouped is-grouped-right" style = "margin-top: 0;">
    <p class="control">
      <%= form.submit "Submit Rant", class: "button is-medium is-primary" %>
    </p>
  </div>
<% end %>

app/views/rants/_rant.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">Rant#<%= rant.id %> - <%= link_to rant.organization.name, rant.organization %></p>
        <p class= "subtitle is-7"><%= time_ago_in_words(rant.created_at) %> ago</p>
      </div>
    </div>

    <div class="content" id="content">
        <%= simple_format rant.body %>
    </div>
    <nav class="level is-mobile" style="margin-top: 1em;">
      <div class="level-left">
        <div class = "level-item">
          <strong>
            Share this rant 
          </strong>
        </div>
        <div class="level-item">
          <a data-toggle="tooltip" title="Share on Facebook" href="https://www.facebook.com/sharer/sharer.php?u=<%= rant_url(rant) %>"><%= fa_icon "facebook" %></a>
        </div>
        <div class="level-item">
          <a data-toggle="tooltip" title="Share on Twitter" href="https://twitter.com/intent/tweet?text=<%= rant_url(rant) %>"><%= fa_icon "twitter" %></a>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/rants/edit.html.erb
<h1>Editing Rant</h1>

<%= render 'form', rant: @rant %>

<%= link_to 'Show', @rant %> |
<%= link_to 'Back', rants_path %>

app/views/rants/index.html.erb
<section class="section">
  <div class="container">

    <h1 class = "title has-text-centered">Rants about <%= @organization.name %></h1>

    <div class="columns is-multiline">
      <% @rants.each do |rant| %>
        <div class="column is-full">
          <%= render "rants/rant", rant: rant %>
        </div>
      <% end %>

    </div>


  </div>
</section>

app/views/rants/new.html.erb
<%= render "organizations/organization-header", organization: @organization %>
<section class="section">
  <div class="container">
    <h1 class= "title has-text-centered">New Rant</h1>

    <%= render 'form', rant: @rant %>



  </div>
</section>

app/views/rants/show.html.erb
<% content_for :head do %>
<%= display_meta_tags og: { title:  "Rant#" + @rant.id.to_s + " - " + @rant.organization.name , description: @rant.body } %>
<%= display_meta_tags twitter: { title:  "Rant#" + @rant.id.to_s + " - " + @rant.organization.name , description: @rant.body } %>
<% end %>
<%= render "organizations/organization-header", organization: @rant.organization %>

<% title ("Rant#" + @rant.id.to_s).to_s %>

<section class="section">
  <div class="container">
    <%= render "rants/rant", rant: @rant %>

    
    <div class="has-text-centered" style="margin-top: 2em;">
      <%= link_to "Click here to see more rants about " + @rant.organization.name, @rant.organization, class: "button is-info " %>
      
    </div>
  </div>
</section>

app/views/shared/_search-input.html.erb
<%= search_form_for @q do |f| %>
  <div class="field">
    <p class = "control has-icons-left">
      <span class = "icon is-left">
        <%= fa_icon "search" %>

      </span>
      <%= f.text_field :name_cont, placeholder: "Search for Organizations", class: 'input search-query', type: "search", "data-autocomplete"  => autocomplete_organization_name_organizations_path%>
    </p>

  </div>
<% end %>

app/views/static_pages/community_guidelines.html.erb
<section class="section">
  <div class="container">
<h1 class = "title is-1 has-text-centered" align="center">
    Community Guidelines
</h1>
<h2 class = "title is-2">
    Foreword
</h2>
<p>
    Our goal with Spill Street is to make an open community where people can
    talk about things that they’re normally afraid to talk about publicly. We
    want to be able to give a voice to the people that are normally voiceless;
    whether it’s due to fear of being ostracized by the community, or due to
    other reasons, we want to be able to help people speak out about
    organizations and communities that are toxic or harmful to its members.
</p>
<p>
    We advocate freedom of speech within our members.
</p>
<p>
    With that said, there are a couple things that don’t sit well with us here.
    It’s important to have freedom of speech, but your freedom shouldn’t be
    made by taking a freedom someone else. So here we have a list of guidelines
    our community must observe.
</p>
<br>
<p>
    <strong>
        Any posts, rants, or comments that go against the community guidelines
        will be removed from the public site without warning.
    </strong>
</p>
<br>
<h2 class = "title is-2">
    Guidelines
</h2>
<p>
    Note: “Individual” in this case refers to a singular member of an
    organization/group/company that is identified. Any rules regarding an
    Individual also applies if more than one Individual is identified in a
    single post, rant, or comment and can be referred to as “Individuals”. If a
    group of people are named, but none of the people in the group are
    individually identified, then they do not fall under “Individual” or
    “Individuals” and are considered an “Organization” or “Organizations”.
</p>
<p>
    1. Any type of bullying and harassment of individuals is not allowed on the
    site. You’re allowed to post about Organizations but targeting it towards
    an Individual of the organization is not allowed. This includes but does
    not pertain to:
</p>
<p>
    a. Identifying an Individual on the site in methods that include but does
    not pertain to:
</p>
<p>
    i. Stating the name of an Individual
</p>
<p>
    ii. Stating any nicknames that a community identifies as an Individual
</p>
<p>
    iii. Stating any titles that refer specifically to an Individual. (Note
    that referring to groups such as “the exec board” or “the members” is
    allowed)
</p>
<p>
    iv. Any other methods in which one can refer to an Individual person in an
    organization
</p>
<p>
    b. Any threats towards the members of an organization.
</p>
<p>
    c. Posting of pictures or videos containing an Individual.
</p>
<p>
    d. Posting links or urls of social media pages of an Individual.
</p>
<p>
    e. Any other action that can constitute as the bullying or harassment of an
    Individual.
</p>
<p>
    2. Libel or otherwise illegal defamations of an Organization or Individual
    can be subject to legal action. While the site promotes freedom of
    expression, libel is still a criminal offense. Actions that constitute as
    libel/illegal defamation are actions that pertain but are not limited to:
</p>
<p>
    a. The posting, ranting, or commenting of fake information that is meant to
    defame an Individual or Organization
</p>
<p>
    b. The posting, ranting, or commenting of incorrect information and
    treating it as factual.
</p>
<p>
    c. Any other situation in which the Philippine Government constitutes as
    libel or illegal defamation
</p>
<p>
    <strong>Note: </strong>
    If what you’re saying is true and can be defended as a fact, then whether
    you’re insulting or just uncovering certain events about an Individual or
    Organization, it does not count as libel.
</p>
<p>
    Items on the guidelines can be added or removed and any changes affect
    posts, rants, and comments retroactively.
</p>
<p>
    Thanks for reading and happy ranting!
</p>
  </div>
</section>

app/views/static_pages/privacy_policy.html.erb
<section class="section">
  <div class="container">
<h1 class = "title is-1">Privacy Policy for Spill Street</h1>

<p>At Spill Street, accessible from www.spillstreet.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Spill Street and how we use it.</p>

<p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us through email at spillstreet@gmail.com</p>

<h2 class = "title is-2">Log Files</h2>

<p>Spill Street follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

<h2 class = "title is-2">Cookies and Web Beacons</h2>

<p>Like any other website, Spill Street uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

<h2 class = "title is-2">Google DoubleClick DART Cookie</h2>

<p>Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – <a href="https://policies.google.com/technologies/ads">https://policies.google.com/technologies/ads</a></p>


<h2 class = "title is-2">Privacy Policies</h2>

<P>You may consult this list to find the Privacy Policy for each of the advertising partners of Spill Street. Our Privacy Policy was created with the help of the <a href="https://www.privacypolicygenerator.info">Privacy Policy Generator</a>.</p>

<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on Spill Street, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

<p>Note that Spill Street has no access to or control over these cookies that are used by third-party advertisers.</p>

<h2 class = "title is-2">Third Party Privacy Policies</h2>

<p>Spill Street's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You may find a complete list of these Privacy Policies and their links here: Privacy Policy Links.</p>

<p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. What Are Cookies?</p>

<h2 class = "title is-2">Children's Information</h2>

<p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

<p>Spill Street does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>

<h2 class = "title is-2">Online Privacy Policy Only</h2>

<p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Spill Street. This policy is not applicable to any information collected offline or via channels other than this website.</p>

<h2 class = "title is-2">Consent</h2>

<p>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</p>


  
    
  </div>
</section>